apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-benchmark-job
  namespace: demo-guidellm
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: guidellm-benchmark
    spec:
      restartPolicy: Never
      volumes:
        - name: models-volume
          emptyDir: {}
        - name: results-volume
          persistentVolumeClaim:
            claimName: guidellm-data
      initContainers:
        - name: gpt-oss-20b-tokenizer
          image: quay.io/redhat-ai-services/modelcar-catalog:gpt-oss-20b
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu
              mkdir -p /shared-results/tokenizers
              cp /models/tokenizer*.json /shared-models/
              cp /models/tokenizer*.json /shared-results/tokenizers/
          volumeMounts:
            - name: models-volume
              mountPath: /shared-models
            - name: results-volume
              mountPath: /shared-results
      containers:
        - name: guidellm
          image: ghcr.io/vllm-project/guidellm:v0.5.3
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu
              TS="$(date -u +%Y%m%dT%H%M%SZ)"
              OUT="/results/guidellm-benchmark-${TS}.json"

              echo "Tokenizer files available in /config:"
              ls -la /config
              echo "Writing benchmark results to ${OUT}"

              guidellm benchmark run \
                --target "${GUIDELLM_TARGET}" \
                --model gpt-oss-20b \
                --processor /config \
                --data "prompt_tokens=5000,output_tokens=1000" \
                --rate-type concurrent \
                --rate 1 \
                --max-seconds 30 \
                --output-path "${OUT}"

              echo "Benchmark complete."
          env:
            - name: GUIDELLM_TARGET
              value: "https://redhataillama-31-8b-instruct-guidellm.apps.cluster-s8mpx.s8mpx.sandbox5256.opentlc.com/v1"
          volumeMounts:
            - name: models-volume
              mountPath: /config
            - name: results-volume
              mountPath: /results
