apiVersion: v1
kind: Pod
metadata:
  name: pvc-reader
  namespace: demo-guidellm
spec:
  restartPolicy: Never
  containers:
    - name: reader
      image: registry.access.redhat.com/ubi9/ubi-minimal
      command: ["/bin/sh","-c","sleep 3600"]
      volumeMounts:
        - name: results
          mountPath: /results
  volumes:
    - name: results
      persistentVolumeClaim:
        claimName: guidellm-data